#!/usr/bin/env python
import re
from sys import argv
word=argv[1] #'76d4984'
f=open('/usr/share/dict/words').read().split("\n")
a=list(f[:-1])
regex=re.compile(r'^[A-Za-z]+$')
words=list(filter(lambda x: regex.match(x), a))
commitwords=word.split('.')

numbers=[]

for w in commitwords:
    numbers.append(words.index(w))

shift = 0;
numbers.reverse()
finalsum = 0
for i in numbers:
    finalsum += i << shift
    shift += 16

print('%0.2x' % finalsum)
