#!/usr/bin/env python
import re
from sys import argv
word=argv[1] #'76d4984'
commitwords=word.split('.')

for w in commitwords:



commitint=int(commit, 16)
regex=re.compile(r'^[A-Za-z]+$')
f=open('/usr/share/dict/words').read().split("\n")
a=list(f[:-1])
words=list(filter(lambda x: regex.match(x), a))
commitwords='%s.%s' % (words[commitint>>16], words[commitint&0xf])
print(commitwords)
